### ISSUE TITLE
socks 9050

### ISSUE THREAD

**Issue by p4tetoh** [samsesh/tor-in-termux#2]
There is an Android  app that listens on 9050 it blocks 9050 for vpn service to some android 10 and legacy devices. hope this helps your success

**Comment by samsesh** [comment]
you can use 9051

**Comment by alanthehat** [comment]
@p4tetoh  are you talking about `Orbot`? 

This should replace it & `Orbot` can be shut down & uninstalled, `Orbot` hasn't handled `HTTP proxy` properly since 2016 anyway

**Comment by 3shadow7** [comment]
i need to unstall this shit

**Comment by samsesh** [comment]
use i2p
